on:
  pull_request:
    branches:
      - master
    # TODO : labeled is used to trigger a restest if this failed.  Find a way for limiting
    # to specifically when we want a retest.  This will rerun when adding semver label and we
    # don't want that
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Install dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d
    
    - name: Lint
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d
    
    - name: Test
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run coverage-missing