on:
  pull_request:
    branches:
      - master

jobs:
  pr_check:
    runs-on: ubuntu-latest   
    name: PR check to ensure unit tests and linting pass
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout Lamb Westin GitHub Actions Repo
      uses: actions/checkout@v2
      with:
        repository: LambWestonIT/github-actions
        ref: 1.0.0
        token: ${{ secrets.GIT_HUB_TOKEN }}
        path: .github/actions/github-actions 
    - uses: ./.github/actions/github-actions/python/dependencies
    - uses: ./.github/actions/github-actions/python/lint
    - uses: ./.github/actions/github-actions/python/unittest

